import { parseSchedule } from "./schedule";

export const DIVISIONS = [
  "AFC North",
  "AFC South",
  "AFC East",
  "AFC West",
  "NFC North",
  "NFC South",
  "NFC East",
  "NFC West",
];

// TODO: Type better
export function isDivisionInConference(division: string, conference: string) {
  return division.startsWith(conference);
}

export interface Team {
  name: string;
  shorthand: string;
  division: string;
}

const TEAMS_OBJECTS = {
  "Arizona Cardinals": { shorthand: "ARI", division: "NFC West" },
  "Atlanta Falcons": { shorthand: "ATL", division: "NFC South" },
  "Baltimore Ravens": { shorthand: "BAL", division: "AFC North" },
  "Buffalo Bills": { shorthand: "BUF", division: "AFC East" },
  "Carolina Panthers": { shorthand: "CAR", division: "NFC South" },
  "Chicago Bears": { shorthand: "CHI", division: "NFC North" },
  "Cincinnati Bengals": { shorthand: "CIN", division: "AFC North" },
  "Cleveland Browns": { shorthand: "CLE", division: "AFC North" },
  "Dallas Cowboys": { shorthand: "DAL", division: "NFC East" },
  "Denver Broncos": { shorthand: "DEN", division: "AFC West" },
  "Detroit Lions": { shorthand: "DET", division: "NFC North" },
  "Green Bay Packers": { shorthand: "GB", division: "NFC North" },
  "Houston Texans": { shorthand: "HOU", division: "AFC South" },
  "Indianapolis Colts": { shorthand: "IND", division: "AFC South" },
  "Jacksonville Jaguars": { shorthand: "JAX", division: "AFC South" },
  "Kansas City Chiefs": { shorthand: "KC", division: "AFC West" },
  "Las Vegas Raiders": { shorthand: "LV", division: "AFC West" },
  "Los Angeles Rams": { shorthand: "LAR", division: "NFC West" },
  "Los Angeles Chargers": { shorthand: "LAC", division: "AFC West" },
  "Miami Dolphins": { shorthand: "MIA", division: "AFC East" },
  "Minnesota Vikings": { shorthand: "MIN", division: "NFC North" },
  "New England Patriots": { shorthand: "NE", division: "AFC East" },
  "New Orleans Saints": { shorthand: "NO", division: "NFC South" },
  "New York Giants": { shorthand: "NYG", division: "NFC East" },
  "New York Jets": { shorthand: "NYJ", division: "AFC East" },
  "Philadelphia Eagles": { shorthand: "PHI", division: "NFC East" },
  "Pittsburg Steelers": { shorthand: "PIT", division: "AFC North" },
  "San Francisco 49ers": { shorthand: "SF", division: "NFC West" },
  "Seattle Seahawks": { shorthand: "SEA", division: "NFC West" },
  "Tampa Bay Buccaneers": { shorthand: "TB", division: "NFC South" },
  "Tennessee Titans": { shorthand: "TEN", division: "AFC South" },
  "Washington Commanders": { shorthand: "WSH", division: "NFC East" },
};

export const TEAMS: Team[] = Object.entries(TEAMS_OBJECTS).reduce(
  (acc, cur) => {
    acc.push({ name: cur[0], ...cur[1] } as never);
    return acc;
  },
  []
);

export const NFC_TEAMS = TEAMS.filter((team) =>
  isDivisionInConference(team.division, "NFC")
);
export const AFC_TEAMS = TEAMS.filter((team) =>
  isDivisionInConference(team.division, "AFC")
);

// Clean this up
export const TEAM_MAP = TEAMS.reduce<Record<string, Team>>((acc, team) => {
  acc[team.shorthand] = team;
  return acc;
}, {});

const PLAYED_GAMES = {
  ARI: [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    null,
    false,
    false,
    true,
  ],
  ATL: [
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    null,
    true,
    true,
    false,
    false,
    true,
    false,
  ],
  BAL: [
    true,
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    null,
    true,
    true,
    true,
    true,
  ],
  BUF: [
    false,
    true,
    true,
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    null,
    true,
    true,
    true,
    true,
  ],
  CAR: [
    false,
    false,
    false,
    false,
    false,
    false,
    null,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
  ],
  CHI: [
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
    null,
    true,
    false,
    true,
    true,
  ],
  CIN: [
    false,
    false,
    true,
    false,
    true,
    true,
    null,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
  ],
  CLE: [
    true,
    false,
    true,
    false,
    null,
    true,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
  ],
  DAL: [
    true,
    true,
    false,
    true,
    false,
    true,
    null,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    true,
  ],
  DEN: [
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    true,
    null,
    true,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
  ],
  DET: [
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    true,
    null,
    true,
    true,
    false,
    true,
    false,
    true,
    true,
    false,
  ],
  GB: [
    true,
    false,
    true,
    false,
    false,
    null,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
  ],
  HOU: [
    false,
    false,
    true,
    true,
    false,
    true,
    null,
    false,
    true,
    true,
    true,
    false,
    true,
    false,
    true,
    false,
    true,
  ],
  IND: [
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    null,
    true,
    true,
    false,
    true,
    false,
    true,
  ],
  JAX: [
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    null,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
  ],
  KC: [
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    null,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
  ],
  LV: [
    false,
    false,
    true,
    true,
    null,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
  ],
  LAR: [
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    null,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
  ],
  LAC: [
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    false,
    false,
    null,
    false,
    true,
    true,
    false,
  ],
  MIA: [
    true,
    true,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    null,
    true,
    true,
    true,
    false,
    true,
    true,
    false,
  ],
  MIN: [
    false,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    true,
    false,
    false,
    false,
  ],
  NE: [
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null,
    false,
    false,
    true,
    false,
    true,
    false,
  ],
  NO: [
    true,
    true,
    false,
    false,
    true,
    false,
    false,
    true,
    true,
    false,
    null,
    false,
    false,
    true,
    true,
    false,
    true,
  ],
  NYG: [
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    null,
    true,
    false,
    false,
    false,
  ],
  NYJ: [
    true,
    false,
    false,
    false,
    true,
    true,
    null,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
  ],
  PHI: [
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    null,
    true,
    true,
    false,
    false,
    false,
    true,
    false,
  ],
  PIT: [
    false,
    true,
    true,
    false,
    true,
    null,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
  ],
  SF: [
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
  ],
  SEA: [
    false,
    true,
    true,
    true,
    null,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
  ],
  TB: [
    true,
    true,
    false,
    true,
    null,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    false,
  ],
  TEN: [
    false,
    true,
    false,
    true,
    false,
    false,
    null,
    true,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
  ],
  WSH: [
    true,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    null,
    false,
    false,
    false,
  ],
};

export const SCHEDULE = parseSchedule(
  `
ARI @WSH NYG DAL @SF CIN @LAR @SEA BAL @CLE ATL @HOU LAR @PIT BYE SF @CHI @PHI SEA
ATL CAR GB @DET @JAX HOU WSH @TB @TEN MIN @ARI BYE NO @NYJ TB @CAR IND @CHI @NO
BAL HOU @CIN IND @CLE @PIT @TEN DET @ARI SEA CLE CIN @LAC BYE LAR @JAX @SF MIA PIT
BUF @NYJ LV @WSH MIA JAX NYG @NE TB @CIN DEN NYJ @PHI BYE @KC DAL @LAC NE @MIA
CAR @ATL NO @SEA MIN @DET @MIA BYE HOU IND @CHI DAL @TEN @TB @NO ATL GB @JAX TB
CHI GB @TB @KC DEN @WSH MIN LV @LAC @NO CAR @DET @MIN BYE DET @CLE ARI ATL @GB
CIN @CLE BAL LAR @TEN @ARI SEA BYE @SF BUF HOU @BAL PIT @JAX IND MIN @PIT @KC CLE
CLE CIN @PIT TEN BAL BYE SF @IND @SEA ARI @BAL PIT @DEN @LAR JAX CHI @HOU NYJ @CIN
DAL @NYG NYJ @ARI NE @SF @LAC BYE LAR @PHI NYG @CAR WSH SEA PHI @BUF @MIA DET @WSH
DEN LV WSH @MIA @CHI NYJ @KC GB KC BYE @BUF MIN CLE @HOU @LAC @DET NE LAC @LV
DET @KC SEA ATL @GB CAR @TB @BAL LV BYE @LAC CHI GB @NO @CHI DEN @MIN @DAL MIN
GB @CHI @ATL NO DET @LV BYE @DEN MIN LAR @PIT LAC @DET KC @NYG TB @CAR @MIN CHI
HOU @BAL IND @JAX PIT @ATL NO BYE @CAR TB @CIN ARI JAX DEN @NYJ @TEN CLE TEN @IND
IND JAX @HOU @BAL LAR TEN @JAX CLE NO @CAR @NE BYE TB @TEN @CIN PIT @ATL LV HOU
JAX @IND KC HOU ATL @BUF IND @NO @PIT BYE SF TEN @HOU CIN @CLE BAL @TB CAR @TEN
KC DET @JAX CHI @NYJ @MIN DEN LAC @DEN MIA BYE PHI @LV @GB BUF @NE LV CIN @LAC
LV @DEN @BUF PIT @LAC GB NE @CHI @DET NYG NYJ @MIA KC BYE MIN LAC @KC @IND DEN
LAR @SEA SF @CIN @IND PHI ARI PIT @DAL @GB BYE SEA @ARI CLE @BAL WSH NO @NYG @SF
LAC MIA @TEN @MIN LV BYE DAL @KC CHI @NYJ DET @GB BAL @NE DEN @LV BUF @DEN KC
MIA @LAC @NE DEN @BUF NYG CAR @PHI NE @KC BYE LV @NYJ @WSH TEN NYJ DAL @BAL BUF
MIN TB @PHI LAC @CAR KC @CHI SF @GB @ATL NO @DEN CHI BYE @LV @CIN DET GB @DET
NE PHI MIA @NYJ @DAL NO @LV BUF @MIA WSH IND BYE @NYG LAC @PIT KC @DEN @BUF NYJ
NO TEN @CAR @GB TB @NE @HOU JAX @IND CHI @MIN BYE @ATL DET CAR NYG @LAR @TB ATL
NYG DAL @ARI @SF SEA @MIA @BUF WSH NYJ @LV @DAL @WSH NE BYE GB @NO @PHI LAR PHI
NYJ BUF @DAL NE KC @DEN PHI BYE @NYG LAC @LV @BUF MIA ATL HOU @MIA WSH @CLE @NE
PHI @NE MIN @TB WSH @LAR @NYJ MIA @WSH DAL BYE @KC BUF SF @DAL @SEA NYG ARI @NYG
PIT SF CLE @LV @HOU BAL BYE @LAR JAX TEN GB @CLE @CIN ARI NE @IND CIN @SEA @BAL
SF @PIT @LAR NYG ARI DAL @CLE @MIN CIN BYE @JAX TB @SEA @PHI SEA @ARI BAL @WSH LAR
SEA LAR @DET CAR @NYG BYE @CIN ARI CLE @BAL WSH @LAR SF @DAL @SF PHI @TEN PIT @ARI
TB @MIN CHI PHI @NO BYE DET ATL @BUF @HOU TEN @SF @IND CAR @ATL @GB JAX NO @CAR
TEN @NO LAC @CLE CIN @IND BAL BYE ATL @PIT @TB @JAX CAR IND @MIA HOU SEA @HOU JAX
WSH ARI @DEN BUF @PHI CHI @ATL @NYG PHI @NE @SEA NYG @DAL MIA BYE @LAR @NYJ SF DAL`,
  PLAYED_GAMES
);
